@startuml Cas 1
title Afegir un nou model de vehicle
actor administrador 
participant "user:Fàbrica" as fabric
participant "inventari:Inventari_Peces" as inventari
participant "inventari_subministrador:Inventari_Peces" as inventarisubministrador
participant "subministrador:Subministrador" as subministrador
participant "peces_cotxe:Peces" as peces
participant "inventari_cotxe:Inventari_Peces" as inventaricotxe
participant "mcotxe:Model_cotxe" as cotxe

group Setup (construction)
    administrador -> fabric: <<create>>
    administrador -> inventari: <<create>>
    administrador -> fabric: setinventari(inventari)
    note right: Afegim el inventari a la fabrica
    administrador -> inventarisubministrador: <<create>>
    administrador -> subministrador: <<create>>
    administrador -> subministrador: setinventari(inventari_subministrador)
    administrador -> peces: <<create>>
    administrador -> inventaricotxe: <<create>>
    administrador -> cotxe: <<create>>
    note right 
    En el cas de model cotxe, rodes ve fixat a 4 
    i la etiqueta de contaminació es calcula mit-
    jançant el tipus de combustible i si es elèc-
    tric o no. La funció calcular_etiqueta(motor
    _electric:bool, tipus_combustible: str)
    end note
end

group Afegir model 
    administrador -> fabric: afegir_model(cotxe) 
    note right : S'afegeix el model al registre de models
end

@enduml 