@startuml Fábrica de cotxes

class Linia_Producció {
    id: str
}
abstract class Model{
-marca: str 
-motor_electric: bool
-cilindrada: float
-etiqueta_contaminació: str
-rodes: int
-peces: dict
}
class Model_cotxe {
    -portes: int
    -tipus_canvi_marxes: str
    -tipus_combustible: str
    -rodes = int 4
}
class Model_motos {
    -motor_electric: bool = False
    -tipus_rodes: str
    -tipus_carnet_conduir: str 
    -tipus_combustible: str = "gasolina"
    -etiqueta_contaminació: str = B
    -rodes: int = 2

}
class Peces {
    -codi: int
    -nom: str
    -descripció: str
    -subministrador: Subministrador
}
class Subministrador {
    -nom: str
    -CIF: int
    -adreça: str
    -país: str
    -inventari: Inventari_Peces

}
class Inventari_Peces {
    -inventari: dict
}
class Registre_producció {
    -vehicle: Vehicle_produït
    -data: date
    -linia_producció: Linia_Producció
}
class Vehicle_produït {
    -Model: Model 
    -num_serie: int
    -color: str
}
class Fàbrica {
-inventari_peces: Inventari_Peces
-registre_models: list
-registre_producció: list
+afegir_model(model)
+produir_vehicle(model, num_serie, color) -> Vehicle_produït 
+consulta_peces_inventari(codi)
+consulta_peces_proveidor(codi, inventari_proveidor)
+consulta_vehicle_per_data(data, model)
+consulta_posibilitat_produccio(model): bool
}
Model <|-- Model_cotxe
Model <|-- Model_motos
Vehicle_produït o-->Model
Registre_producció o--> Vehicle_produït
Registre_producció o--> Linia_Producció
Fàbrica o--> Registre_producció
Peces o--> Subministrador
Inventari_Peces <--o Subministrador
Inventari_Peces *--> Peces
Fàbrica o-->Inventari_Peces
Model o-->Peces

@enduml

