@startuml Fábrica de cotxes

class Linia_Producció {
    id: str
}
abstract class Model{
-nom: str 
-motor_electric: bool
-cilindrada: float
-/etiqueta_contaminació: str
-rodes: int
-peces: Inventari_Peces
+getmotor_electric(): bool
+getpeces(): Inventari_Peces
+setpeces(inventari: Inventari_Peces)
+calcular_etiqueta(motor_electric: bool, tipus_combustible: str): str
}
class Model_cotxe {
    -portes: int
    -tipus_canvi_marxes: str
    -tipus_combustible: str
    -rodes: int = 4
    +setportes(portes:int)
    +calcular_etiqueta(motor_electric: bool, tipus_combustible: str) -> str
}
class Model_motos {
    -motor_electric: bool = False
    -tipus_rodes: str
    -tipus_carnet_conduir: str 
    -tipus_combustible: str = "gasolina"
    -rodes: int = 2
    +calcular_etiqueta(motor_electric: bool, tipus_combustible: str) -> str()

}
class Peces {
    -codi: int
    -nom: str
    -descripció: str
    -subministrador: Subministrador
    +getcodi(): int
}
class Subministrador {
    -nom: str
    -CIF: int
    -adreça: str
    -país: str
    -inventari: Inventari_Peces
    +getpeces(): Inventari_Peces
    +setpeces(inventari: Inventari_Peces)
    +elimina_peces(codi, quantitat)

}
class Inventari_Peces {
    -inventari: dict
    +getinventari(): dict
    +afegir_peces_inventari(peça,quantitat)
    +elimina_peces(codi, quantitat)
    +mostrar_peces()
}
class Linia_inventari {
    -peça: Peces
    -quantitat: int
    +getquantitat(): int
    +setquantitat(quantitat:int)
}
class Registre_producció {
    -vehicle: Vehicle_produït
    -\data: date
    -linia_produccio: Linia_Producció 
    +calcular_data(): date
    +getdate(): date
    +getvehicle(): vehicle 
    +data_coincidence(data) -> bool
    +model_coincidence(model) -> bool
}
class Vehicle_produït {
    -Model: Model 
    -num_serie: int
    -color: str
    +GetModel() -> Model
}
class Fàbrica {
-inventari_peces: Inventari_Peces
-registre_models: list
-registre_producció: list
+getinventari(): Inventari_Peces
+setinventari(inventari:Inventari_Peces)
+afegir_model(model: Model)
+afegir_peces_inventari(peça:Peces, quantitat:int)
+afegir_vehicle_produit(vehicle: Vehicle_produït, data: date, linia: Linia_Producció)
+elimina_peces(codi:int, quantitat:int)
+consulta_peces_inventari(codi:int): bool
+consulta_peces_proveidor(codi:int, subministrador:Subministrador): bool
+consulta_vehicle_per_data(data:date, model:Model): int
+consulta_posibilitat_produccio(model): bool
}
Model <|-- Model_cotxe
Model <|-- Model_motos
Model *--> Inventari_Peces
Vehicle_produït o-->Model
Registre_producció o--> Vehicle_produït
Registre_producció o--> Linia_Producció
Fàbrica o--> Registre_producció
Peces o--> Subministrador
Inventari_Peces <--o Subministrador
Inventari_Peces o--> Peces
Inventari_Peces *--> Linia_inventari
Fàbrica o-->Inventari_Peces

@enduml

